@echo off
echo Starting React Frontend...
cd frontend
echo Current directory: %CD%
echo Checking if node_modules exists...
if not exist "node_modules" (
    echo Installing dependencies...
    npm install
)
echo Starting React development server...
npm start
pause 