# Generated by Django 4.2.7 on 2025-08-07 06:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('coordinates', models.JSONField(help_text='List of coordinate pairs [[lng, lat], ...]')),
                ('area_sq_meters', models.DecimalField(decimal_places=2, help_text='Area in square meters', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('perimeter_meters', models.DecimalField(decimal_places=2, help_text='Perimeter in meters', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Polygon',
                'verbose_name_plural': 'Polygons',
                'ordering': ['-created_at'],
            },
        ),
    ]
